project:
  type: website
  output-dir: _site

website:
  title: "Mismas estadísticas, gráficos distintos"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: explainer.qmd
        text: Explicación

format:
  html:
    theme: cosmo
    toc: true
    css: assets/style.css
    include-in-header:
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/@observablehq/plot@0.6"></script>
          <script src="https://cdn.jsdelivr.net/npm/d3@7"></script>